version: '3'

services:
  page-parser:
    image: versta-page-parser:local
    container_name: versta-page-parser
    environment:
      HTTP_PORT: 8080
      LOG_LEVEL: DEBUG
      ORDERS_SERVICE_HOST: ""
    ports:
      - "8080:8080"
    volumes:
      - ./landing-page-parser/app.log:/go/app.log
